name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.anthony8800 }}
          password: ${{ secrets.ANTHONY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t yourdockerhubusername/my-python-app:latest .

      - name: Push Docker image to DockerHub
        run: docker push yourdockerhubusername/my-python-app:latest
