name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: "anthony8800"         # 👈 Your DockerHub username
          password: "ANTHONY_PASSWORD"    # 👈 Your DockerHub password

      - name: Build Docker image
        run: docker build -t anthony8800/my-python-app:latest .

      - name: Push Docker image to DockerHub
        run: docker push anthony8800/my-python-app:latest
